### ISSUE TITLE
Implement Reidentify

### ISSUE THREAD

**Issue by TinaTiel** [obs-websocket-community-projects/obs-websocket-java#86]
https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#reidentify

**Comment by ChristopheCVB** [comment]
Since we are not allowing developers to register event listeners after creation, it is not useful to implement it.
With that in mind, it means that devs have to register all the events they want at creation and they will be fired for the whole life of the OBSRemoteController. This is not ideal, they maybe want to register and unregister on the fly and implementing that mechanism is what will trigger a Reidentify imho.

**Comment by TinaTiel** [comment]
Agreed

**Comment by ChristopheCVB** [comment]
Why closing it? We meet want to implement this for v2.x+1 ?
